use_frameworks!

target 'simple_keyboard_layout_guide_Example' do
  pod 'simple_keyboard_layout_guide', :path => '../'

  target 'simple_keyboard_layout_guide_Tests' do
    inherit! :search_paths

    
  end
end
